version: "3"
volumes:
  work:
    driver: local

services:
  notebook:
    image: avinson/cuda-prophet:1.0.0rc4
    runtime: nvidia
    volumes:
      - work:/home/jovyan/work:cached
    ports:
      - 8888:8888
    user: root
    environment:
      GRANT_SUDO: 'yes'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]