version: "3"
volumes:
  work:
    driver: local

services:
  notebook:
    image: cuda
    runtime: nvidia
    volumes:
      - work:/home/jovyan/work:cached
    ports:
      - 8888:8888
    user: root
    environment:
      GRANT_SUDO: 'yes'
    command: start-notebook.sh --NotebookApp.custom_display_url=http://localhost:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]